### ISSUE TITLE
Showing the report in Python scripts

### ISSUE THREAD

**Issue by banesullivan** [banesullivan/scooby#26]
Recently, a user became a bit stumped on how to show a report in their Python script: see https://github.com/pyvista/pyvista-support/issues/20#issuecomment-507272061

They wanted to generate and show the report right after importing all their modules because they were experiencing a bug that would crash the kernel

Should we add a note in the README that users might have to call `print(scooby.Report())`

**Comment by prisae** [comment]
Well, half of the problem was because of `investigate`->`Report`, that is unfortunate but that error should be gone now (we're still <1, so allowed to make API changes ;-) )

> Should we add a note in the README that users might have to call print(scooby.Report())

Maybe you could add a note that if you are in a notebook, and do not scooby at the end of a cell, then you have to explicitly print it; but then it won't render a table.
